(* Roughly, a class of FOL formulas is said to be a reduction class if its
 * satisfiability is undecidable. We strengthen this definition slightly
 * in order to also conveniently obtain the undecidability of validity
 * and provability without having to assume LEM in the metatheory. *)
From Undecidability.FOL Require Import
  FullSyntax PrenexNormalForm
  FriedmanValidity FriedmanTranslation.
From Undecidability.Synthetic Require Import Undecidability ReducibilityFacts.

Existing Instance falsity_on.

(* A generic formula bundles the signature with the formula *)
Record gform := Mk_gform
  { g_funcs : funcs_signature
  ; g_preds : preds_signature
  ; g_funcs_list : cListable g_funcs
  ; g_preds_list : cListable g_preds
  ; g_form : form g_funcs g_preds
  }.

Coercion g_form : gform >-> form.

(* A FOL class is a predicate that, given a listable signature and a formula
 * over that signature, reports whether said formula belongs to the class. *)
Definition FOL_class := gform -> Prop.

(* A reduction class is a FOL class such that... *)
Record FOL_reduction_class (C : FOL_class) : Type := Mk_reduction_class
  (* all formulas in the class are conjuctions of prenex formulas; *)
  { rc_isPNF : forall phi, C phi -> PNF_conj phi
  (* and there exists some problem whose complement is undecidable... *)
  ; rc_X : Type
  ; rc_problem : rc_X -> Prop
  ; rc_problem_undec : undecidable (complement rc_problem)

  (* from which there is a reduction to the satisfiability of formulas in the class *)
  ; rc_formula : forall x : rc_X, gform
  ; rc_form_in_C : forall x : rc_X, C (rc_formula x)

  ; rc_carrier : forall x : rc_X, Type
  ; rc_inh     : forall x : rc_X, inhabited (rc_carrier x)
  ; rc_interp  : forall x : rc_X, interp (rc_carrier x)
  ; rc_sat     : forall x : rc_X, ~ rc_problem x -> rc_interp x ⊨= rc_formula x

  ; rc_sound : forall (x : rc_X) D (I : interp D) (rho : env D), sat I rho (rc_formula x) -> ~ rc_problem x

  (* such that the models generated by the reduction are decidable
   * (even though the other direction of the reduction doesn't get to assume this) *)
  ; rc_interp_dec : forall x : rc_X, interp_dec (rc_interp x)
  }.

Arguments rc_problem       {C} _.
Arguments rc_problem_undec {C} _.

Section FixSig.
  Context {Σ_funcs : funcs_signature}.
  Context {Σ_preds : preds_signature}.
  Context {ff : falsity_flag}.

  (* Satisfiability by a decidable model *)
  Definition dec_satis phi := exists D (I : interp D) rho,
    interp_dec I /\ rho ⊨ phi.

  (* Validity in decidable models *)
  Definition dec_valid phi := forall D (I : interp D) rho,
    interp_dec I -> rho ⊨ phi.
End FixSig.

Section Problems.
  Local Unset Implicit Arguments.

  Definition FOL_class_satis (C : FOL_class) : { phi : gform | C phi } -> Prop :=
    fun 'phi => satis (proj1_sig phi).

  Definition FOL_class_dec_satis (C : FOL_class) : { phi : gform | C phi } -> Prop :=
    fun 'phi => dec_satis (proj1_sig phi).

  Definition FOL_class_valid (C : FOL_class) : { phi : gform | C phi } -> Prop :=
    fun 'phi => valid (¬ proj1_sig phi).

  Definition FOL_class_dec_valid (C : FOL_class) : { phi : gform | C phi } -> Prop :=
    fun 'phi => dec_valid (¬ proj1_sig phi).

  Definition FOL_class_prv (C : FOL_class) : { phi : gform | C phi } -> Prop :=
    fun 'phi => prv (p := class) nil (¬ proj1_sig phi).
End Problems.

Section ProblemsUndec.
  Context {C : FOL_class}.
  Hypothesis Hrc : FOL_reduction_class C.

  Definition redfunc (x : rc_X Hrc) := exist _ (rc_formula x) (rc_form_in_C x).

  Lemma prob_dsatis x : ~ rc_problem Hrc x -> FOL_class_dec_satis C (redfunc x).
  Proof.
    intros Hx. unfold FOL_class_satis, satis, redfunc; simpl.
    destruct (rc_inh x) as [a].
    exists (rc_carrier x), (rc_interp x), (fun _ => a).
    split.
    + apply rc_interp_dec.
    + now apply rc_sat.
  Qed.

  Lemma satis_prob x : FOL_class_satis C (redfunc x) -> ~ rc_problem Hrc x.
  Proof.
    intros (D & I & rho & Hsat).
    apply (rc_sound Hsat).
  Qed.

  Lemma dsatis_satis phi : FOL_class_dec_satis C phi -> FOL_class_satis C phi.
  Proof.
    - intros (D & I & rho & Hdec & Hsat).
      now exists D, I, rho.
  Qed.

  Lemma satis_red : complement (rc_problem Hrc) ⪯ FOL_class_satis C.
  Proof.
    exists redfunc.
    split.
    - intros H.
      now apply dsatis_satis, prob_dsatis.
    - intros (D & I & rho & Hsat).
      apply (rc_sound Hsat).
  Qed.


  Lemma prob_valid x : ~ ~ rc_problem Hrc x -> FOL_class_valid C (redfunc x).
  Proof.
    intros Hnsat D I rho Hsat. cbn.
    apply Hnsat, satis_prob.
    now exists D, I, rho.
  Qed.

  Lemma dvalid_prob x : FOL_class_dec_valid C (redfunc x) -> ~ ~ rc_problem Hrc x.
  Proof.
    intros Hdvalid Hsat%prob_dsatis.
    destruct Hsat as (D & I & rho & Hdec & Hsat).
    exact (Hdvalid D I rho Hdec Hsat).
  Qed.

  Lemma nprob_ndvalid x : ~ rc_problem Hrc x -> ~ FOL_class_dec_valid C (redfunc x).
  Proof.
    now intros Hnprob Hprob%dvalid_prob.
  Qed.

  Lemma nvalid_nprob x : ~ FOL_class_valid C (redfunc x) -> ~ rc_problem Hrc x.
  Proof.
    intros Hnvalid Hprob.
    now apply Hnvalid, prob_valid.
  Qed.


  Lemma valid_red : complement (FOL_class_satis C) ⪯ FOL_class_valid C.
  Proof using Hrc.
    exists id; split.
    - intros Hnsat D I rho Hsat. cbn.
      apply Hnsat.
      now exists D, I, rho.
    - intros Hvalid (D & I & rho & Hsat).
      exact (Hvalid D I rho Hsat).
  Qed.


  Lemma prv_red : complement (rc_problem Hrc) ⪯ complement (FOL_class_prv C).
  Proof.
    exists redfunc; split.
    - intros Hnvalid%nprob_ndvalid Hprv%Fr_cl_to_min.
      apply Hnvalid.
      intros D I rho Hdec.
      apply soundness' in Hprv.
      apply PNF_conj_neg_Fr_sat.
      + exact Hdec.
      + apply (rc_isPNF Hrc).
        apply proj2_sig.
      + apply Hprv.
    - intros Hnprv. apply nvalid_nprob. intros Hvalid.
      (* valid Ko (redfunc x)? *)
      (* TODO: completeness should hold constructively even for Full FOL *)
      admit.
  Admitted.

  Theorem FOL_class_satis_compl_undec : undecidable (complement (FOL_class_satis C)).
  Proof using Hrc.
    apply (undecidability_from_reducibility (undecidability_to_complement (rc_problem_undec Hrc))).
    apply reduces_complement, satis_red.
  Qed.

  Theorem FOL_class_satis_undec : undecidable (FOL_class_satis C).
  Proof using Hrc.
    apply undecidability_from_complement, FOL_class_satis_compl_undec.
  Qed.

  Theorem FOL_class_valid_undec : undecidable (FOL_class_valid C).
  Proof using Hrc.
    apply (undecidability_from_reducibility FOL_class_satis_compl_undec).
    apply valid_red.
  Qed.

  Theorem FOL_class_prv_compl_undec : undecidable (complement (FOL_class_prv C)).
  Proof using Hrc.
    eapply (undecidability_from_reducibility (rc_problem_undec Hrc)).
    apply prv_red.
  Qed.

  Theorem FOL_class_prv_undec : undecidable (FOL_class_prv C).
  Proof using Hrc.
    apply undecidability_from_complement, FOL_class_prv_compl_undec.
  Qed.

End ProblemsUndec.
